


<hr class="linecolor" width="690" align="left">
<table align="left" width="690">
<tr>
				<td class="footer" align="center" colSpan="3"><IMG height="10" src="images/pix.gif"></td>
				</tr>
				<tr>
					<td class="footer" align="center" colSpan="3">For website technical problems/comments/suggestions , 
						contact fafs.careers@aub.edu.lb
						
						AUB's <a href="http://www.aub.edu.lb/aub_files/copyright.html">Copyright</a> and
						<a href="http://www.aub.edu.lb/aub_files/disclaimer.html">Disclaimer</a></td>
				</tr>
			</table>
			
			</body></center>