



<table  width="690">
			
				<tr>
					<td class="footer"  colSpan="3">
						<p align="center">For web problems/comments or suggestions , 
						contact >fafs.careers@aub.edu.lb
						
						AUB's <a href="http://www.aub.edu.lb/aub_files/copyright.html">Copyright</a> and
						<a href="http://www.aub.edu.lb/aub_files/disclaimer.html">Disclaimer</a>
						</p>
					</td>
				</tr>
				
			</table>
			
			