

	<table cellSpacing="0" cellPadding="0" border="0" width="690" >
				<tr>
					<td vAlign="top"><a href="http://www.aub.edu.lb/fafs"><IMG  src="../images/fafs.jpg" border="0" ></a></td>
					<td valign="middle">
					&nbsp;&nbsp;&nbsp;&nbsp;<img align="left" src="images/title.jpg" >
						
						</td>
					<td valign="middle">
					<td ><a href="http://www.aub.edu.lb/"><IMG  src="../images/aub.jpg" border="0" ></a></td>
					</td>
				</tr>
				
				</table>
				<hr class="linecolor" align="left" width="690" >
			
				
		