<head><LINK href="includes/style.css" type="text/css" rel="STYLESHEET"></head>

<body>	<table align="center" cellSpacing="0" cellPadding="0" border="0">
				<tr>
					<td vAlign="bottom"><IMG height="67" src="images/logo.jpg" width="69">
					</td>
					<td class="title" vAlign="bottom" width="73%">FAFS Career Center<br>
						<IMG height="10" src="images/pix.gif" width="8"></td>
					<td width="18%"><IMG height="52" src="images/aub_logo.gif" width="144"></td>
				</tr>
				<tr>
					<td bgColor="#50555e" colSpan="3"><IMG height="1" src="images/pix.gif" width="2"></td>
				</tr>
				<tr>
					<td class="hmenu" align="right" colSpan="3" height="5"><a href=Logout.aspx target=_top>Home</a><IMG height="20" src="images/pix.gif" width="5%" align="middle"><a href="http://www.aub.edu.lb" target=_blank>AUB</a>
						<IMG height="20" src="images/pix.gif" width="5%" align="middle"><a href="http://www.aub.edu.lb/fea" target=_blank>FEA</a>
						<IMG height="20" src="images/pix.gif" width="5%" align="middle"><a href=FAQ.aspx target=_top> FAQ </a> <IMG height="20" src="images/pix.gif" width="5%"><a href=Announcements.aspx target=_top>Announcements</a>
						<IMG height="20" src="images/pix.gif" width="5%" align="middle"><a href=internship_offers/internshipoffers.xls target=_blank>Internship Offers</a><IMG height="20" src="images/pix.gif" width="5%" align="middle"><a href="mailto:fafs.careers@aub.edu.lb">Contact 
						Us</a><IMG height="20" src="images/pix.gif" width="3%" align="middle"><a href=AboutUs.aspx target=_top>About Us</a></td>
				</tr>
				<tr>
					<td bgColor="#50555e" colSpan="3"><IMG height="1" src="images/pix.gif" width="2"></td>
				</tr>
				</table>
			
				
		